import type { BoomLift, ContactInfo } from './types';

export const CONTACT_INFO: ContactInfo = {
  phone: "+91 92210 28139",
  phone2: "+91 93245 25581",
  email: "oginworldwide@gmail.com",
  // Registered office, supplied by the client on 2026-10-03.
  address: {
    street: "Green Avenue, Bungalow No. 2",
    locality: "Mira Road East",
    city: "Thane",
    region: "Maharashtra",
    postalCode: "401107",
    country: "India"
  }
};

export const BOOM_LIFTS: BoomLift[] = [
  {
    id: "660sj",
    slug: "jlg-660sj",
    model: "660SJ",
    brand: "JLG",
    platformHeight: "20.12 m (66 ft)",
    horizontalOutreach: "17.30 m (56 ft 9 in)",
    platformCapacity: "230 kg (500 lb)",
    weight: "11,476 kg",
    heightM: 20.12,
    outreachM: 17.30,
    capacityKg: 230,
    weightKg: 11476,
    nominalHeightFt: 66,
    description: "The JLG 660SJ offers a large work envelope and high capacity in a compact frame. Rented with a certified professional operator.",
    imageUrl: "/images/660sj.webp",
    imageWidth: 1080,
    imageHeight: 1080,
    features: ["Includes Professional Operator", "Oscillating Axle", "Easy to Transport", "Durable Construction"]
  },
  {
    id: "860sj",
    slug: "jlg-860sj",
    model: "860SJ",
    brand: "JLG",
    platformHeight: "26.21 m (86 ft)",
    horizontalOutreach: "22.86 m (75 ft)",
    platformCapacity: "230 kg (500 lb)",
    weight: "16,465 kg",
    heightM: 26.21,
    outreachM: 22.86,
    capacityKg: 230,
    weightKg: 16465,
    nominalHeightFt: 86,
    description: "The JLG 860SJ telescopic boom lift features a fuel-efficient Tier 4 engine and provides a large work envelope. Rented with a certified professional operator for maximum safety.",
    imageUrl: "/images/860sj.webp",
    imageWidth: 1600,
    imageHeight: 1200,
    features: ["Includes Professional Operator", "Oscillating Axle", "Hydraulic Platform Rotation", "Tilt Light and Alarm"]
  },
  {
    id: "1200sjp",
    slug: "jlg-1200sjp",
    model: "1200SJP",
    brand: "JLG",
    platformHeight: "36.58 m (120 ft)",
    horizontalOutreach: "22.86 m (75 ft)",
    platformCapacity: "454 kg (1,000 lb)",
    weight: "18,552 kg",
    heightM: 36.58,
    outreachM: 22.86,
    capacityKg: 454,
    weightKg: 18552,
    nominalHeightFt: 120,
    description: "The 1200SJP offers the reach and capacity you need for demanding jobsites. All rentals include an experienced operator to ensure precision and safety.",
    imageUrl: "/images/1200sjp.webp",
    imageWidth: 1600,
    imageHeight: 1200,
    features: ["Includes Professional Operator", "Dual Capacity", "Extendable Axles", "360 Degree Continuous Rotation"]
  },
  {
    id: "1350sjp",
    slug: "jlg-1350sjp",
    model: "1350SJP",
    brand: "JLG",
    platformHeight: "41.15 m (135 ft)",
    horizontalOutreach: "24.38 m (80 ft)",
    platformCapacity: "454 kg (1,000 lb)",
    weight: "20,411 kg",
    heightM: 41.15,
    outreachM: 24.38,
    capacityKg: 454,
    weightKg: 20411,
    nominalHeightFt: 135,
    description: "Go from the ground to 135 ft in under 95 seconds. The 1350SJP provides exceptional stability. Rented exclusively with our skilled operators.",
    imageUrl: "/images/1350sjp.webp",
    imageWidth: 1600,
    imageHeight: 1200,
    features: ["Includes Professional Operator", "Fastest Lift Speed", "JibPLUS® Boom", "Four-Wheel Hydrostatic Drive"]
  },
  {
    id: "1500sj",
    slug: "jlg-1500sj",
    model: "1500SJ",
    brand: "JLG",
    platformHeight: "45.72 m (150 ft)",
    horizontalOutreach: "24.38 m (80 ft)",
    platformCapacity: "454 kg (1,000 lb)",
    weight: "22,000 kg",
    heightM: 45.72,
    outreachM: 24.38,
    capacityKg: 454,
    weightKg: 22000,
    nominalHeightFt: 150,
    description: "The JLG 1500SJ is one of the largest self-propelled telescopic booms available, perfect for massive industrial projects. Rented with an expert operator.",
    imageUrl: "/images/1500sj.webp",
    imageWidth: 1600,
    imageHeight: 1200,
    features: ["Includes Professional Operator", "Telescoping Jib", "Dual Capacity", "Exceptional Stability"]
  },
  {
    id: "s60j",
    slug: "genie-s60j",
    model: "S-60 J",
    brand: "Genie",
    platformHeight: "18.50 m (60 ft 8 in)",
    horizontalOutreach: "12.30 m (40 ft 5 in)",
    platformCapacity: "300 kg (660 lb)",
    weight: "7,550 kg",
    heightM: 18.50,
    outreachM: 12.30,
    capacityKg: 300,
    weightKg: 7550,
    nominalHeightFt: 60,
    description: "The Genie S-60 J is a lightweight and high-performance boom lift designed for essential tasks. Rented with a certified professional operator.",
    imageUrl: "/images/s60j.webp",
    imageWidth: 2000,
    imageHeight: 2000,
    features: ["Includes Professional Operator", "Lightweight Design", "Active Oscillation", "Low Maintenance"]
  },
  {
    id: "s85xc",
    slug: "genie-s85xc",
    model: "S-85 XC",
    brand: "Genie",
    platformHeight: "25.91 m (85 ft)",
    horizontalOutreach: "22.71 m (74 ft 6 in)",
    platformCapacity: "454 kg (1,000 lb)",
    weight: "18,000 kg",
    heightM: 25.91,
    outreachM: 22.71,
    capacityKg: 454,
    weightKg: 18000,
    nominalHeightFt: 85,
    description: "The Genie S-85 XC is a high-capacity boom lift offering dual capacity and fuel efficiency. Rented exclusively with our skilled operators.",
    imageUrl: "/images/s85xc.webp",
    imageWidth: 750,
    imageHeight: 1428,
    features: ["Includes Professional Operator", "Dual Capacity (300/454 kg)", "Rough Terrain Capability", "Smooth Control"]
  }
];

export const TRANSLATIONS = {
  nav_call: "Call to Rent",
  hero_badge: "Premium Access Solutions",
  hero_title_1: "Reach Higher with",
  hero_title_2: "JLG & Genie",
  hero_title_3: "Boom Lifts",
  hero_desc: "OG-IN Worldwide LLP provides India's most reliable fleet of high-altitude telescopic boom lifts. All equipment is rented with certified professional operators.",
  hero_cta_1: "Explore Fleet",
  hero_cta_2: "Why Choose Us",
  fleet_title: "Our Premium Fleet",
  fleet_desc: "Select from our range of high-performance JLG and Genie telescopic boom lifts, maintained to the highest international standards and operated by experts.",
  card_height: "Height",
  card_outreach: "Outreach",
  card_btn: "View Specifications",
  trust_title: "The OG-IN Advantage",
  trust_desc: "We provide the reliability and expert manpower your high-altitude projects demand.",
  trust_1_title: "Expert Operators",
  trust_1_desc: "Every rental includes a certified, highly-trained operator to manage the equipment safely.",
  trust_2_title: "Certified Safety",
  trust_2_desc: "All our lifts undergo rigorous multi-point safety inspections before every deployment.",
  trust_3_title: "Pan-India Delivery",
  trust_3_desc: "Efficient logistics network to deliver equipment and operators to your jobsite anywhere in India.",
  trust_4_title: "Maximum Uptime",
  trust_4_desc: "Modern fleet with low operational hours ensures your project stays on schedule without delays.",
  cta_title: "Ready to start your project?",
  cta_desc: "Our experts are ready to help you choose the right equipment and operator for your needs. Call us now for a custom quote.",
  cta_hours: "Available Monday - Saturday, 9:00 AM - 7:00 PM",
  modal_tech_specs: "Technical Specs",
  modal_features: "Key Features",
  modal_rent_prompt: "Ready to rent this model?",
  modal_contact_desk: "Contact our rental desk",
  footer_desc: "India's premier destination for high-reach telescopic boom lift rentals with professional operators. Specializing in JLG and Genie equipment.",
  footer_links: "Quick Links",
  footer_contact: "Contact Us",
  footer_rights: "All rights reserved.",
  with_operator: "With Professional Operator"
};
