import type { BoomLift, PostalAddress } from '../types';
import { CONTACT_INFO, TRANSLATIONS } from '../constants';
import { fill, liftVars } from './fleet';

/**
 * Page titles and meta descriptions, assembled from constants.ts.
 *
 * Every figure here is read from the BoomLift record; nothing is restated, rounded
 * or invented. No claim about certification, compliance, pricing or availability
 * appears in any of these strings beyond what the site already says.
 */

const BRAND_SUFFIX = 'OG-IN Worldwide';

/** The one place a machine URL is built. Trailing slash matches trailingSlash: 'always'. */
export const liftPath = (lift: BoomLift) => `/fleet/${lift.slug}/`;

/** Share image for a machine page, generated by `npm run og` (scripts/og-images.mjs). */
export const ogImagePath = (lift: BoomLift) => `/og/${lift.slug}.jpg`;
export const liftImageAlt = (lift: BoomLift) => `${lift.brand} ${lift.model} telescopic boom lift`;

/** "+91 98765 43210" -> "+919876543210" (E.164, for tel: links and JSON-LD). */
export const e164 = (phone: string) => `+${phone.replace(/\D/g, '')}`;
export const telHref = (phone: string) => `tel:${e164(phone)}`;

/** wa.me wants the number as bare digits with country code, no "+". */
export const whatsappHref = (text?: string) =>
  `https://wa.me/${CONTACT_INFO.whatsapp.replace(/\D/g, '')}` +
  (text ? `?text=${encodeURIComponent(text)}` : '');

/** WhatsApp opening message: names the machine when there is one. */
export const waPrefill = (lift?: BoomLift) =>
  lift ? fill(TRANSLATIONS.wa_prefill_lift, liftVars(lift)) : TRANSLATIONS.wa_prefill_generic;

/** Display lines for an address. JSON-LD addressLocality uses the same "locality, city" pairing. */
export const addressLocality = (a: PostalAddress) => `${a.locality}, ${a.city}`;
export const formatAddress = (a: PostalAddress) => [
  a.street,
  addressLocality(a),
  `${a.region} ${a.postalCode}`,
  a.country,
];

/** Google truncates around these lengths; exceeded values are reported by `npm run seo`. */
export const TITLE_MAX = 60;
export const DESCRIPTION_MAX = 160;

export const liftTitle = (lift: BoomLift) =>
  `${lift.brand} ${lift.model} Boom Lift Rental — ${lift.nominalHeightFt} ft | ${BRAND_SUFFIX}`;

export const liftDescription = (lift: BoomLift) =>
  `${lift.brand} ${lift.model} boom lift on rent, pan-India from Mumbai. ` +
  `${lift.platformHeight} platform height, ${lift.platformCapacity} max. capacity. Certified operator included.`;

export const FLEET_TITLE = fill(`Boom Lift Fleet: JLG & Genie, {minHeightFt}–{maxHeightFt} ft | ${BRAND_SUFFIX}`);
export const FLEET_DESCRIPTION = fill(
  '{fleetCount} JLG and Genie telescopic boom lifts for hire pan-India, {minHeightFt}–{maxHeightFt} ft platform height. ' +
  'Compare specs. Certified operator included.',
);

export const CONTACT_TITLE = `Contact: Boom Lift Rental Quotes | ${BRAND_SUFFIX}`;
export const CONTACT_DESCRIPTION =
  'Call, WhatsApp or send the quote form for boom lift rental. Mumbai-based, pan-India hire, ' +
  'certified operator included. Mon–Sat, 9:00 AM–7:00 PM.';

export const HIGHREACH_TITLE = fill(`High Reach Boom Lift Rental, {highReachMinFt}–{maxHeightFt} ft | ${BRAND_SUFFIX}`);
export const HIGHREACH_DESCRIPTION = fill(
  'Hire JLG telescopic boom lifts at {highReachHeightsFt} ft platform height ' +
  'with a certified operator. Mumbai-based, pan-India. Get a quote.',
);

export const GUIDE_TITLE = `Boom Lift Working Height: How to Choose | ${BRAND_SUFFIX}`;
export const GUIDE_DESCRIPTION =
  'Platform height vs working height, outreach, capacity, ground and access: how to pick a boom lift ' +
  'or manlift for the job, with the full fleet spec table.';

export const PRIVACY_TITLE = `Privacy Policy | ${BRAND_SUFFIX}`;
export const PRIVACY_DESCRIPTION =
  'What the OG-IN Worldwide quote form collects, how enquiry details are used and stored, ' +
  'and how to ask for your data to be accessed or deleted.';

export const THANKS_TITLE = `Enquiry Received | ${BRAND_SUFFIX}`;
export const THANKS_DESCRIPTION =
  'Your boom lift rental enquiry has reached OG-IN Worldwide. ' +
  'We will contact you by phone or WhatsApp during working hours, Mon–Sat.';

export const HOME_TITLE = `Boom Lift Rental Mumbai & Pan-India | ${BRAND_SUFFIX}`;
export const HOME_DESCRIPTION = fill(
  'Boom lift and manlift rental from Mumbai, pan-India. JLG and Genie telescopic booms, ' +
  '{minHeightFt}–{maxHeightFt} ft platform height, certified operator on every hire.',
);
